### ISSUE TITLE
你好，能仅提供错误的那部分图像的修正zip吗

### ISSUE THREAD

**Issue by Eloise-z** [SunnyHaze/CASIA2.0-Corrected#3]
你好，能仅提供错误的那部分图像的修正zip吗，全部有2.5G太大了
Hi, can you only provide the correction zip of the wrong part of the image?

**Comment by SunnyHaze** [comment]
Send me an email, xiaochen.ma.cs@gmail.com, please.

**Comment by Eloise-z** [comment]
My email is ***@***.***
thanks

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SunnyHaze/CASIA2.0-Corrected-Groundtruth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月12日(星期五) 晚上6:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SunnyHaze/CASIA2.0-Corrected-Groundtruth] 你好，能仅提供错误的那部分图像的修正zip吗 (Issue #3)





 
Send me an email, ***@***.***, please.
