### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Yguang0419** [SunnyHaze/CASIA2.0-Corrected#4]
对于我这种一个人搞的，解决数据集的各种问题占用了我大部分时间!

**Comment by SunnyHaze** [comment]
非常感谢你的反馈，这对我们也是鼓励，我也很理解您一个人处理数据集的挑战（因为我也是一个人修正的😴）。

祝科研顺利！

**Comment by Yguang0419** [comment]
真的感谢您对科研认真且负责的态度，（你们在GitHub直接硬怼MVSS-Net真的很赞）


祝您科研顺利！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SunnyHaze/CASIA2.0-Corrected-Groundtruth"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月12日(星期天) 中午1:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SunnyHaze/CASIA2.0-Corrected-Groundtruth] Thanks (Issue #4)





 
非常感谢你的反馈，这对我们也是鼓励，我也很理解您一个人处理数据集的挑战（因为我也是一个人修正的😴）。
 
祝科研顺利！
